title: Ji Yeow Law 
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Agricultural and Civil (Environmental) Engineer with 5 years+ of contribution in environmental monitoring and remediation. 
  Extensive critical thinking (R&D) and problem-solving (consulting) experience serving government, non-profit, and private clients.
  <br><br>
  Specialized in water resources management, water quality monitoring, water treatment, H&H modeling, cost analysis, and big data management.
  <br><br>
  <a href="https://www.linkedin.com/in/ji-yeow-law-eit-bb040b65/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> <br>
  <a href="/pdf/Ji Yeow Law - Resume.pdf">Download my resume</a>
  
theme: jekyll-theme-minimal
google_analytics: G-8ND8RWHYPR # your Google Analytics tracking ID here
