title: Ji Yeow Law 
logo: "/images/Law-Ji Yeow243 round.jpg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/ji-yeow-law-eit-bb040b65/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-8ND8RWHYPR # your Google Analytics tracking ID here
