title: Ji Yeow Law, PE 
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ames, Iowa 50014, USA. <br>
  jiyeowlaw@gmail.com <br><br>
  
  Environmental (Agricultural and Civil) Engineer with 5 years+ of contribution in environmental monitoring and remediation. 
  <br><br>
  Specialized in water resources management, water quality monitoring, water treatment, hydrology, cost analysis, and data science.
  <br><br>
  
  <a href="https://jiyeow.github.io/index.html" rel="noopener noreferrer">Main Page</a> <br> 
  <a href="https://jiyeow.github.io/hobby.html" rel="noopener noreferrer">Hobbies</a> <br><br>
  
  <a href="https://www.linkedin.com/in/jiyeowlaw/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> <br>
  <a href="https://scholar.google.com/citations?user=WJfo4p8AAAAJ&hl=en/" target="_blank" rel="noopener noreferrer">View My Google Scholar</a> <br><br>
  
  <a href="/pdf/Ji Yeow Law - Resume.pdf " target="_blank" rel="noopener noreferrer">Download My Resume</a><br>
  <a href="/pdf/Ji Yeow Law - CV.pdf " target="_blank" rel="noopener noreferrer">Download My CV</a><br>
  <a href="/pdf/Ji Yeow Law - Portfolio.pdf " target="_blank" rel="noopener noreferrer">Download My Portfolio</a> 
  
theme: jekyll-theme-minimal
# gtag('config', 'G-T964P3TZY0')
